<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>TstTargetApplication</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Infrastructure\Controllers\" />
      <Folder Include="Infrastructure\Mappers\" />
      <Folder Include="Infrastructure\Validators\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Infrastructure\Resources\GroupsMockData.json" />
      <_ContentIncludedByDefault Remove="Infrastructure\Resources\UsersMockData.json" />
    </ItemGroup>
    
</Project>
